[build]
  publish = "build"
  command = "bash build.sh"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  SKIP_YARN_COREPACK = "true"
  YARN_PRODUCTION = "false"
  CI = "true"

# Force npm usage by disabling yarn
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200