# Netlify Configuration for React CRA Project
# This file should override any UI settings

[build]
  publish = "build"
  command = "bash build.sh"
  ignore = "/bin/false"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  SKIP_YARN_COREPACK = "true"
  YARN_PRODUCTION = "false"
  CI = "true"
  # Skip Next.js plugin since this is a React CRA project
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Override UI settings
  NETLIFY_BUILD_BASE = ""
  NETLIFY_PUBLISH_PATH = "build"

# Explicitly disable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"


# Force npm usage by disabling yarn
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200